#!/bin/bash

# make sure we are in the relevant folder - the same where this script located
cd $(dirname $BASH_SOURCE)

# activate venv created inside 1-venv-initialization script
source venv/bin/activate

# launch
python3 gamev33.py